[build-system]
requires = ["scikit-build-core>=0.11"]
build-backend = "scikit_build_core.build"

[project]
name = "pyaseba"
version = "0.0.4"
dependencies = [
]
requires-python = ">=3.12"
authors = [
  {name = "Jerome Guzzi", email = "jerome@idsia.ch"},
]
maintainers = [
  {name = "Jerome Guzzi", email = "jerome@idsia.ch"}
]
description = "Unofficial Aseba Python bindings"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["aseba"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/jeguzzi/pyaseba"
Documentation = "https://jeguzzi.github.io/pyaseba/"
Repository = "https://github.com/jeguzzi/pyaseba.git"
"Bug Tracker" = "https://github.com/jeguzzi/pyaseba/issues"
Changelog = "https://github.com/jeguzzi/pyaseba/blob/main/CHANGELOG.md"


[project.optional-dependencies]

all = [
  'rich'
]

 
[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.define = {}
install.components = ["pyaseba"]
wheel.exclude = ["__pycache__"]
