import collections.abc
import typing
from .msgs import Message

class Description:
    @property
    def _variables_map(self) -> dict[str, tuple[int, int]]: ...
    @property
    def events(self) -> list[tuple[str, str]]: ...
    @property
    def functions(self) -> list[tuple[str, str, list[tuple[str, int]]]]: ...
    @property
    def name(self) -> str: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def variables(self) -> list[tuple[str, int]]: ...

class Event:
    @property
    def data(self) -> list[int]: ...
    @property
    def name(self) -> str: ...
    @property
    def source(self) -> int: ...

class Network:
    def __init__(self) -> None: ...
    def _close(self) -> None: ...
    def _connect(self, target: str) -> bool: ...
    def _start(self) -> None: ...
    def _stop(self) -> None: ...
    def add_connection_callback(self, callback: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex], None]) -> None: ...
    def add_disconnection_callback(self, callback: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex], None]) -> None: ...
    def add_event_callback(self, callback: collections.abc.Callable[[Event], None]) -> None: ...
    def add_message_callback(self, callback: collections.abc.Callable[[Message], None]) -> None: ...
    def close(self) -> None: ...
    def connect(self, target: str, wait_ms: typing.SupportsInt | typing.SupportsIndex = ..., max_retries: typing.SupportsInt | typing.SupportsIndex = ...) -> bool: ...
    def emit_event(self, node: typing.SupportsInt | typing.SupportsIndex, name: str, payload: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = ...) -> None: ...
    def get_description(self, node: typing.SupportsInt | typing.SupportsIndex) -> Description | None: ...
    def get_event(self, node: typing.SupportsInt | typing.SupportsIndex = ..., name: str = ..., wait_ms: typing.SupportsInt | typing.SupportsIndex = ..., callback: collections.abc.Callable[[Event], None] = ...) -> Event: ...
    def get_message(self, node: typing.SupportsInt | typing.SupportsIndex = ..., type: typing.SupportsInt | typing.SupportsIndex = ..., wait_ms: typing.SupportsInt | typing.SupportsIndex = ..., callback: collections.abc.Callable[[Message], None] = ...) -> Message | None: ...
    def get_user_events(self, node: typing.SupportsInt | typing.SupportsIndex) -> list[str]: ...
    def get_variable(self, node: typing.SupportsInt | typing.SupportsIndex, name: str, wait_ms: typing.SupportsInt | typing.SupportsIndex, callback: collections.abc.Callable[[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], None] = ...) -> list[int] | None: ...
    def get_variables(self, node: typing.SupportsInt | typing.SupportsIndex) -> list[str]: ...
    def has_node(self, node: typing.SupportsInt | typing.SupportsIndex) -> bool: ...
    def load_script(self, node: typing.SupportsInt | typing.SupportsIndex, script: str, events: collections.abc.Sequence[tuple[str, int]] = ..., constants: collections.abc.Sequence[tuple[str, int]] = ...) -> None: ...
    def pause(self, node: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def reset(self, node: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def run(self, node: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def send_event(self, node: typing.SupportsInt | typing.SupportsIndex, type: typing.SupportsInt | typing.SupportsIndex, payload: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = ...) -> None: ...
    def send_message(self, message: Message) -> None: ...
    def send_user_message(self, type: typing.SupportsInt | typing.SupportsIndex, payload: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = ...) -> None: ...
    def set_variable(self, node: typing.SupportsInt | typing.SupportsIndex, name: str, value: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def set_variables(self, node: typing.SupportsInt | typing.SupportsIndex, index: typing.SupportsInt | typing.SupportsIndex, values: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def sleep(self, node: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def stop(self, node: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def wait_disconnection(self, wait_ms: typing.SupportsInt | typing.SupportsIndex = ..., callback: collections.abc.Callable[[bool], None] = ...) -> bool | None: ...
    def wait_node_connection(self, node: typing.SupportsInt | typing.SupportsIndex = ..., wait_ms: typing.SupportsInt | typing.SupportsIndex = ..., callback: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex], None] = ...) -> int | None: ...
    def wait_node_disconnection(self, node: typing.SupportsInt | typing.SupportsIndex = ..., wait_ms: typing.SupportsInt | typing.SupportsIndex = ..., callback: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex], None] = ...) -> int | None: ...
    @property
    def _nodes(self) -> dict[int, Description]: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def nodes(self) -> list[int]: ...
