from collections.abc import Sequence
from typing import ClassVar

class Description:
    @property
    def functions(self) -> dict[str, tuple[str, list[tuple[str, int]]]]: ...
    @property
    def local_events(self) -> dict[str, str]: ...
    @property
    def name(self) -> str: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def variables(self) -> dict[str, tuple[int, int]]: ...

class Network:
    def __init__(self, address: str = ..., port: int = ..., advertised_name: str = ...) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def spin(self, time_step: float, duration: float = ...) -> None: ...
    async def spin_async(self, time_step: float, duration: float = ...) -> None: ...
    def start(self, time_step: float, duration: float = ...) -> None: ...
    def stop(self) -> None: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...

class Node:
    events: ClassVar[dict[str, str]]
    variables: ClassVar[dict[str, int]]
    functions: ClassVar[dict[str, tuple[str, Sequence[tuple[str, int]]]]]

    def __init__(self, node_id: int, name: str = ..., default_variables: bool = ..., default_functions: bool = ..., uuid: Sequence[int] = ..., advertised_name: str = ...) -> None: ...
    def emit(self, name: str) -> None: ...
    def get(self, name: str) -> list[int]: ...
    def get_all(self) -> dict[str, list[int]]: ...
    def set(self, name: str, value: Sequence[int]) -> None: ...
    @property
    def description(self) -> Description: ...
    @property
    def name(self) -> str: ...
    @property
    def node_id(self) -> int: ...

def _init_logger() -> None: ...
def _set_logger_level(name: str) -> None: ...
