import collections.abc

class Node:
    def __init__(self, node_id: int, name: str) -> None: ...
    def emit(self, name: str) -> None: ...
    def get(self, name: str) -> list[int]: ...
    def set(self, name: str, value: collections.abc.Sequence[int]) -> None: ...

class Network:
    def __init__(self, address: str = ..., port: int = ..., timeout: int = ..., advertise_as: str = ...) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def spin(self, time_step: float) -> bool: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...
