from collections.abc import Sequence
from typing import Any

class Network:
    def __init__(self, address: str = ..., port: int = ..., advertised_name: str = ...) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def spin(self, time_step: float, duration: float = ...) -> None: ...
    def start(self, time_step: float, duration: float = ...) -> None: ...
    def stop(self) -> None: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...

class Node:
    def __init__(self, node_id: int, name: str = ..., default_variables: bool = ..., default_functions: bool = ..., uuid: Sequence[int] = ..., advertised_name: str = ...) -> None: ...
    def emit(self, name: str) -> None: ...
    def get(self, name: str) -> list[int]: ...
    def get_all(self) -> dict[str, list[int]]: ...
    def set(self, name: str, value: Sequence[int]) -> None: ...
    @property
    def description(self) -> Any: ...
    @property
    def name(self) -> str: ...
