import types
from typing import Any, Self
from collections.abc import Callable, Sequence
from . import msgs

DescriptionFragment = msgs.Description | msgs.LocalEventDescription | msgs.NamedVariableDescription | msgs.NativeFunctionDescription


class Client:
    automatic_query: bool
    ping_period_ms: int
    pause_processing: bool
    node_disconnection_timeout_ms: int
    @property
    def port(self) -> int: ...
    def __init__(self, port: int = ..., address: str = ..., ping_period_ms: int = ..., automatic_query: bool = ..., min_protocol_version: int = ..., max_protocol_version: int = ...) -> None: ...
    def _connect(self, target: str) -> int: ...
    def _start(self) -> None: ...
    def _stop(self) -> None: ...
    def add_connection_callback(self, callback: Callable[[int, str], None]) -> None: ...
    def add_disconnection_callback(self, callback: Callable[[int, str], None]) -> None: ...
    def add_event_callback(self, callback: Callable[[Event], None]) -> None: ...
    def add_message_callback(self, callback: Callable[[Message, int], None]) -> None: ...
    def add_node_callback(self, callback: Callable[[int, int], None]) -> None: ...
    def add_node_disconnection_callback(self, callback: Callable[[int, int], None]) -> None: ...
    def advertise(self, name: str = ..., nodes: Sequence[tuple[int, int, str]] = ..., protocol_version: int = ...) -> None: ...
    def advertise_nodes(self, name: str = ..., specs: dict[str, tuple[str, int]] = ..., query_product_id: bool = ..., protocol_version: int = ...) -> None: ...
    def clear_incoming_messages(self) -> None: ...
    def clear_message_callbacks(self) -> None: ...
    def close(self) -> None: ...
    def close_connection(self, connection: int) -> bool: ...
    def cmd_pause(self, node_id: int, include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def cmd_reset(self, node_id: int, include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def cmd_run(self, node_id: int, include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def cmd_sleep(self, node_id: int, include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def cmd_stop(self, node_id: int, include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def connect(self, target: str, wait_ms: int = ..., max_retries: int = ..., **kwargs: Any) -> int: ...
    def deadvertise(self, name: str) -> None: ...
    def emit_event(self, node_id: int, name: str, payload: Sequence[int] = ..., include: set[int] = ..., exclude: set[int] = ...) -> Description | None: ...
    def get_all_variables(self, node_id: int, wait_ms: int = ..., callback: Callable[[list[int]], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> dict[str, list[int]]: ...
    def get_description(self, node_id: int, include: set[int] = ..., exclude: set[int] = ..., connected: bool = ...) -> Description | None: ...
    def get_descriptions(self, include: set[int] = ..., exclude: set[int] = ..., connected: bool = ...) -> dict[int, dict[int, Description]]: ...
    def get_event(self, node_id: int, name: str, wait_ms: int = ..., callback: Callable[[Event], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> Event | None: ...
    def get_message(self, node_id: int = ..., types: set[int] = ..., wait_ms: int = ..., callback: Callable[[Message, int], None] | None = ..., include: set[int] = ..., exclude: set[int] = ..., pause: bool = ...) -> tuple[Message | None, int]: ...
    def get_node_ids(self, include: set[int] = ..., exclude: set[int] = ..., connected: bool = ...) -> dict[int, set[int]]: ...
    def get_changed_variables(self, node_id: int, wait_ms: int = ..., callback: Callable[[list[tuple[int, list[int]]]], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> list[tuple[int, list[int]]]: ...
    def get_variable(self, node_id: int, name: str, wait_ms: int = ..., callback: Callable[[list[int]], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> list[int]: ...
    def get_variable_by_index(self, node_id: int, index: int, length: int, wait_ms: int = ..., callback: Callable[[list[int]], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> list[int]: ...
    def has_node(self, node_id: int, include: set[int] = ..., exclude: set[int] = ..., connected: bool = ...) -> bool: ...
    def load_script(self, node_id: int, script: str, events: dict[str, int] = ..., constants: dict[str, int] = ..., include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def ping(self) -> None: ...
    def query_description(self, node_id: int, wait_ms: int = ..., callback: Callable[[Description], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> Description | None: ...
    def query_description_fragment(self, node_id: int, fragment: int, wait_ms: int = ..., callback: Callable[[DescriptionFragment], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> DescriptionFragment | None: ...
    def remove_message_callback(self, index: int) -> None: ...
    def scan(self, number: int = -1, wait_ms: int = ..., callback: Callable[[int, int, bool], None] | None = ...) -> dict[int, set[int]]: ...
    def send_event(self, type: int, payload: Sequence[int] = ..., include: set[int] = ..., exclude: set[int] = ...) -> Description | None: ...
    def send_message(self, message: Message, include: set[int] = ..., exclude: set[int] = ...) -> Description | None: ...
    def send_user_message(self, type: int = ..., payload: Sequence[int] = ..., include: set[int] = ..., exclude: set[int] = ...) -> Description | None: ...
    def set_variable(self, node_id: int, name: str, value: Sequence[int], wait_ms: int = ..., include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def set_variable_by_index(self, node_id: int, index: int, value: Sequence[int], wait_ms: int = ..., include: set[int] = ..., exclude: set[int] = ...) -> None: ...
    def wait_connection(self, connection: int = ..., wait_ms: int = ..., callback: Callable[[int], None] = ...) -> tuple[int, str]: ...
    def wait_disconnection(self, connection: int = ..., wait_ms: int = ..., callback: Callable[[int], None] = ...) -> tuple[int, str]: ...
    def wait_node(self, node_id: int = ..., wait_ms: int = ..., callback: Callable[[int, int], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> tuple[int, int]: ...
    def wait_node_disconnection(self, node_id: int = ..., wait_ms: int = ..., callback: Callable[[int, int], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> tuple[int, int]: ...
    def wait_nodes(self, node_ids: set[int] = ..., number: int = ..., wait_ms: int = ..., callback: Callable[[dict[int, set[int]], bool], None] | None = ..., include: set[int] = ..., exclude: set[int] = ...) -> dict[int, set[int]]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    @property
    def _is_running(self) -> bool: ...
    @property
    def connections(self) -> dict[int, str]: ...
    @property
    def descriptions(self) -> dict[int, dict[int, Description]]: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def node_ids(self) -> dict[int, set[int]]: ...

class Description:
    @property
    def functions(self) -> dict[str, tuple[str, list[tuple[str, int]]]]: ...
    @property
    def local_events(self) -> dict[str, str]: ...
    @property
    def name(self) -> str: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def user_events(self) -> dict[str, int]: ...
    @property
    def variables(self) -> dict[str, tuple[int, int]]: ...
    @property
    def variables_by_index(self) -> dict[int, tuple[str, int]]: ...

class Event:
    @property
    def data(self) -> list[int]: ...
    @property
    def name(self) -> str: ...
    @property
    def source(self) -> int: ...

class Message:
    source: int
    type: int

def _init_logger() -> None: ...
def _set_logger_level(level: str) -> None: ...
def complete_target(target: str, **kwargs: Any) -> str: ...
def scan_serial_ports() -> dict[int, tuple[str, str]]: ...
def supports_logging() -> bool: ...
def uses_mobsya_aseba() -> bool: ...
