import collections.abc

from .msgs import Message


class Client:
    query: bool
    def __init__(self, port: int = ..., query: bool = ...) -> None: ...
    def _close(self) -> None: ...
    def _connect(self, target: str) -> bool: ...
    def _get_variables(self, node: int, index: int, length: int, wait_ms: int, callback: collections.abc.Callable[[collections.abc.Sequence[int]], None] = ...) -> list[int] | None: ...
    def _start(self, ping: bool = ...) -> None: ...
    def _stop(self) -> None: ...
    def add_event_callback(self, callback: collections.abc.Callable[[Event], None]) -> None: ...
    def add_message_callback(self, callback: collections.abc.Callable[[Message, int], None]) -> None: ...
    def add_node_connection_callback(self, callback: collections.abc.Callable[[int], None]) -> None: ...
    def add_node_disconnection_callback(self, callback: collections.abc.Callable[[int], None]) -> None: ...
    def add_target_connection_callback(self, callback: collections.abc.Callable[[int, str], None]) -> None: ...
    def add_target_disconnection_callback(self, callback: collections.abc.Callable[[int, str], None]) -> None: ...
    def clear_incoming_messages(self) -> None: ...
    def clear_message_callbacks(self) -> None: ...
    def close(self) -> None: ...
    def connect(self, target: str, wait_ms: int = ..., max_retries: int = ..., ping: bool = ...) -> bool: ...
    def emit_event(self, node: int, name: str, payload: collections.abc.Sequence[int] = ...) -> None: ...
    def get_description(self, node: int) -> Description: ...
    def get_event(self, node: int = ..., name: str = ..., wait_ms: int = ..., callback: collections.abc.Callable[[Event], None] = ...) -> Event | None: ...
    def get_message(self, node: int = ..., type: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[Message, int], None] = ...) -> tuple[Message | None, int]: ...
    def get_user_events(self, node: int) -> list[str]: ...
    def get_all_variables(self, node: int, wait_ms: int = ..., callback: collections.abc.Callable[[collections.abc.Mapping[str, list[int]]], None] = ...) -> dict[str, list[int]] | None: ...
    def get_variable(self, node: int, name: str, wait_ms: int, callback: collections.abc.Callable[[collections.abc.Sequence[int]], None] = ...) -> list[int] | None: ...
    def get_variables(self, node: int) -> list[str]: ...
    def get_variables_size(self, node: int) -> int: ...
    def has_node(self, node: int) -> bool: ...
    def load_script(self, node: int, script: str, events: collections.abc.Sequence[tuple[str, int]] = ..., constants: collections.abc.Sequence[tuple[str, int]] = ...) -> None: ...
    def pause(self, node: int) -> None: ...
    def ping(self) -> None: ...
    def remove_message_callback(self, index: int) -> None: ...
    def reset(self, node: int) -> None: ...
    def run(self, node: int) -> None: ...
    def send_event(self, node: int, type: int, payload: collections.abc.Sequence[int] = ...) -> None: ...
    def send_message(self, message: Message, target_index: int = ..., exclude_target_indices: collections.abc.Set[int] = ...) -> None: ...
    def send_user_message(self, type: int, payload: collections.abc.Sequence[int] = ...) -> None: ...
    def set_variable(self, node: int, name: str, value: collections.abc.Sequence[int]) -> None: ...
    def set_variables(self, node: int, index: int, values: collections.abc.Sequence[int]) -> None: ...
    def scan(self, number: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[set[int], bool], None] = ...) -> set[int]: ...
    def sleep(self, node: int) -> None: ...
    def stop(self, node: int) -> None: ...
    def wait_node_connection(self, node: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[int], None] = ...) -> int | None: ...
    def wait_node_disconnection(self, node: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[int], None] = ...) -> int | None: ...
    def wait_nodes(self, nodes: collections.abc.Set[int] = ..., number: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[set[int], bool], None] = ...) -> set[int]: ...
    def wait_target_connection(self, index: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[int, str], None] = ...) -> tuple[int, str]: ...
    def wait_target_disconnection(self, index: int = ..., wait_ms: int = ..., callback: collections.abc.Callable[[int, str], None] = ...) -> tuple[int, str]: ...
    @property
    def _nodes(self) -> dict[int, Description]: ...
    @property
    def connected_targets(self) -> dict[int, str]: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def nodes(self) -> list[int]: ...

class Description:
    @property
    def _variables_map(self) -> dict[str, tuple[int, int]]: ...
    @property
    def events(self) -> list[tuple[str, str]]: ...
    @property
    def functions(self) -> list[tuple[str, str, list[tuple[str, int]]]]: ...
    @property
    def name(self) -> str: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def variables(self) -> list[tuple[str, int]]: ...

class Event:
    @property
    def data(self) -> list[int]: ...
    @property
    def name(self) -> str: ...
    @property
    def source(self) -> int: ...

def scan_serial_ports() -> dict[int, tuple[str, str]]: ...
