import collections.abc
import typing

class Server:
    def __init__(self, port: typing.SupportsInt | typing.SupportsIndex = ..., timeout: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def spin(self, time_step: typing.SupportsFloat | typing.SupportsIndex) -> bool: ...

class Node:
    def __init__(self, node_id: typing.SupportsInt | typing.SupportsIndex, name: str) -> None: ...
    def emit(self, name: str) -> None: ...
    def get(self, name: str) -> list[int]: ...
    def set(self, name: str, value: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
