name: Build and test
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-22.04-arm
          - windows-11-arm
          # - macos-latest
        python-version:
          # - "3.12"
          - "3.13"
          # - "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          path: src/pyaseba
      - if: runner.os == 'Linux'
        name: install apt deps
        run: |
          sudo apt-get update
          sudo apt-get install libavahi-compat-libdnssd-dev
      - if: runner.os == 'Windows'
        uses: actions/checkout@v6
        with:
          repository: 'G-P-S/bonjour-win-sdk'
          path: "bonjour-win-sdk"
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: pip install build repairwheel
      - name: build wheel (non-windows)
        if: runner.os != 'Windows'
        run: |
          cd src/pyaseba
          python -m build -w
          repairwheel -o repaired_dist dist/*.whl
      - name: build wheel (windows)
        if: runner.os == 'Windows'
        run: |
          cd src\pyaseba
          python -m build -w --config-setting cmake.define.DNSSD_ROOT=${{ github.workspace }}/bonjour-win-sdk
          $fileNames = Get-ChildItem -Path dist -Recurse -Include *.whl
          repairwheel -o repaired_dist $fileNames[0]
      - name: archive wheel
        uses: actions/upload-artifact@v7
        with:
          name: wheel-${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}
          path: src/pyaseba/repaired_dist/*
          if-no-files-found: error
      - name: install wheel (non windows)
        if: runner.os != 'Windows'
        run: |
          wheels=( src/pyaseba/repaired_dist/*.whl )
          pip install ${wheels[0]}[all]
      - name: install wheel (windows)
        if: runner.os == 'Windows'
        run: |
          $wheels = Get-ChildItem -Path src\pyaseba\repaired_dist -Recurse -Include *.whl
          pip install "$($wheels[0])[all]"
      - name: test import
        run: |
          python -c "import pyaseba"
      - name: test create client
        run: |
          python -c "from pyaseba import Client; Client()"
      - name: test create network
        run: |
          python -c "from pyaseba import Network; Network().spin(0.1, 1)"
      # - name: test ping pong client-client
      #   run: |
      #     python src/pyaseba/examples/ping_pong/client_client/client_client_async.py
      # - name: test ping pong client-network sync
      #   run: |
      #     python src/pyaseba/examples/ping_pong/client_network/function_sync.py
      # - name: test ping pong client-network async
      #   run: |
      #     python src/pyaseba/examples/ping_pong/client_network/function_async.py
